# Generated by Django 3.2.20 on 2023-09-06 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='image',
            field=models.CharField(max_length=64),
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.CharField(max_length=64),
        ),
    ]
