# Generated by Django 3.2.20 on 2023-09-06 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0002_auto_20230906_1204'),
    ]

    operations = [
        migrations.CreateModel(
            name='Texter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('email', models.CharField(max_length=150)),
                ('message', models.TextField()),
            ],
        ),
    ]
