# Generated by Django 3.2.20 on 2023-09-17 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Portfolio', '0003_texter'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Skill',
        ),
    ]
